spring:
  profiles:
    active: local

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml, classpath*:/document/*.xml, classpath*:/ingestion/*.xml
  type-aliases-package: com.argus.rag
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

